---
- hosts: localhost
  connection: local
  #  become: true

  pre_tasks:
  - name: update repositories
    become: true
    apt:
      update_cache: yes
    changed_when: False

  tasks: 
    - include: tasks/packages.yml
    - include: tasks/dotfiles.yml
