---
- hosts: localhost
  connection: local
  become: no
  vars:
   kernel_info: "{{ ansible_kernel }}"
   user_id: "{{ ansible_user_id }}"
   home_dir: "{{ ansible_user_dir }}"
   dotfiles_dir: "{{ ansible_user_dir + '/dotfiles'}}"

  pre_tasks:
  - name: update repositories
    become: true
    apt:
      update_cache: yes
    changed_when: False

  tasks: 
    - include: tasks/packages.yml
    - include: tasks/dotfiles.yml
