# - name: get username
#   become: false
#   local_action: command whoami
#   register: host_name
# 
- debug: var=home_dir
- debug: var=user_id

# - name: print hostname
#   become: false
#   debug: msg="{{ home_dir }}"
