- debug: var=home_dir
- debug: var=user_id
- debug: var=dotfiles_dir

- name: get dotfiles repo
  git:
    repo: git@github.com:NafiAsib/dotfiles.git
    dest: "{{ home_dir }}/dotfiles"

- name: check .config status 
  stat: path=/$HOME/.config
  register: configdir

- name: create .config if doesn't exist
  file:
    path: "{{ home_dir }}/.config"
    state: directory
  when: not configdir.stat.exists

- name: check .cache/zsh status
  stat: path=/$HOME/.cache/zsh
  register: zshcache

- name: create cache dir
  file:
    path: "{{ home_dir }}/.cache/zsh"
    state: directory
  when: not zshcache.stat.exists


- name: print if not exists
  debug:
    msg: "Doesn't exist"
  when: not configdir.stat.exists

- name: print if exists
  debug:
    msg: "exists"
  when: configdir.stat.exists

- name: symlink tmux.conf
  file:
    src: "{{ home_dir }}/dotfiles/.tmux.conf"
    dest: "{{ home_dir }}/.tmux.conf"
    owner: "{{ user_id }}"
    group: "{{ user_id }}"
    state: link
  
# - name: check for zsh-syntax-highlighting
#   stat: path=/$HOME/zsh-syntax-highlighting
#   register: zshsyntax
# 
# - name: clone zsh-syntax-highlighting
#   git:
#     repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
#     dest: "{{ home_dir }}/zsh-syntax-highlighting"
#   when: not zshsyntax.stat.exists
#
# - name: install sharship.rs
#   become: true
#   shell: sh -c "$(curl -fsSL https://starship.rs/install.sh)" -y
# - name: print hostname
#   become: false
#   debug: msg="{{ home_dir }}"
