# - name: get username
#   become: false
#   local_action: command whoami
#   register: host_name
# 
# - debug: var=host_name.stdout

- name: print hostname
  become: false
  debug: msg="{{ lookup('env', 'HOME') }}"
