# - name: get username
#   become: false
#   local_action: command whoami
#   register: host_name
# 
- debug: var=home_dir
- debug: var=user_id

- name: check for zsh-syntax-highlighting
  stat: path=/$HOME/zsh-syntax-highlighting
  register: zshsyntax

- name: clone zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ home_dir }}/zsh-syntax-highlighting"
  when: not zshsyntax.stat.exists

# - name: install sharship.rs
#   become: true
#   shell: sh -c "$(curl -fsSL https://starship.rs/install.sh)" -y
# - name: print hostname
#   become: false
#   debug: msg="{{ home_dir }}"
