# - name: get username
#   become: false
#   local_action: command whoami
#   register: host_name
# 
- debug: var=home_dir
- debug: var=user_id

- name: install sharship.rs
  become: true
  shell: sh -c "$(curl -fsSL https://starship.rs/install.sh)"
# - name: print hostname
#   become: false
#   debug: msg="{{ home_dir }}"
