- name: Install packages
  become: true
  apt:
    name: 
      - python3-psutil
      - neovim
      - tmux
      - htop
      - bpytop
      - tree
      - zsh

- name: change current shell to zsh
  become: yes 
  user: 
    name: "{{ user_id }}"
    shell: /bin/zsh

- name: Pop!_OS specific packages
  become: true
  apt:
    name:
    - dconf-cli
  when: ansible_distribution in ["Pop!_OS", "Ubuntu"]

- name: WSL2 specific packages
  become: true
  apt:
    name:
      - powerline
      - fonts-powerline
  when: '"WSL2" in kernel_info'
