- name: Install packages
  become: true
  apt:
    name: 
      - python3-psutil
      - neovim
      - tmux
      - htop
      - bpytop
      - tree
      - dconf-cli

- name: WSL2 specific packages
  become: true
  kernel_info: ansible_kernel
  apt:
    name:
      - powerline
      - fonts-powerline
  when: '"WSL2" in kernel_info'
